[project]
name = "faststrapy"
version = "0.2.0"
description = "A CLI tool to scaffold production-ready FastAPI projects instantly — inspired by create-next-app, powered by Jinja2 templates and interactive prompts."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "typer>=0.27.0",
    "click>=8.1.0",
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
]

[project.scripts]
faststrapy = "faststrapy.main:app"

[project.urls]
Homepage = "https://github.com/AnoopGeorge418/faststrapy"
Repository = "https://github.com/AnoopGeorge418/faststrapy"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["faststrapy"]

[dependency-groups]
dev = [
    "black>=26.5.1",
]
